/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ecommerce;

<<<<<<< HEAD
import java.util.ArrayList;
=======
<<<<<<< HEAD
=======
import java.util.ArrayList;
>>>>>>> origin/Louisnew
>>>>>>> refs/heads/Aniket2
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.Product;
import model.ProductDirectory;
<<<<<<< HEAD
import util.DatabaseConnector;
=======
<<<<<<< HEAD
=======
import util.DatabaseConnector;
>>>>>>> origin/Louisnew
>>>>>>> refs/heads/Aniket2

/**
 *
 * @author jq
 */
public class viewProductPanel extends javax.swing.JPanel {
<<<<<<< HEAD
=======
<<<<<<< HEAD
    ProductDirectory products;
    /**
     * Creates new form viewProductPanel
     */
    public viewProductPanel(JPanel bottomPanel, ProductDirectory products1) {
        initComponents();
=======
>>>>>>> refs/heads/Aniket2
        private ArrayList<Product> products;
    private Product selectedProduct;
    /**
     * Creates new form viewProductPanel
     */
    public viewProductPanel(JPanel bottomPanel) {
        initComponents();
        populateTable();
<<<<<<< HEAD
=======
>>>>>>> origin/Louisnew
>>>>>>> refs/heads/Aniket2
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        descriptionField = new javax.swing.JTextField();
<<<<<<< HEAD
=======
<<<<<<< HEAD
        viewButton = new javax.swing.JButton();
=======
>>>>>>> origin/Louisnew
>>>>>>> refs/heads/Aniket2
        deleteButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        nameLabel = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        descriptionLabel = new javax.swing.JLabel();
        searchField = new javax.swing.JTextField();
        priceField = new javax.swing.JTextField();
        headingLabel = new javax.swing.JLabel();
<<<<<<< HEAD
        saveButton = new javax.swing.JButton();
=======
<<<<<<< HEAD
=======
        saveButton = new javax.swing.JButton();
>>>>>>> origin/Louisnew
>>>>>>> refs/heads/Aniket2

        userTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
<<<<<<< HEAD
                "productID", "Name", "Price", "Description"
=======
<<<<<<< HEAD
                "Name", "Description"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };
=======
                "Name", "Price", "Description"
>>>>>>> refs/heads/Aniket2
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
<<<<<<< HEAD
=======
>>>>>>> origin/Louisnew
>>>>>>> refs/heads/Aniket2

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(userTable);

        jLabel1.setText("Search");

        descriptionField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descriptionFieldActionPerformed(evt);
            }
        });

<<<<<<< HEAD
=======
<<<<<<< HEAD
        viewButton.setText("View");
        viewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewButtonActionPerformed(evt);
            }
        });

=======
>>>>>>> origin/Louisnew
>>>>>>> refs/heads/Aniket2
        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        nameLabel.setText("Product Name");

        priceLabel.setText(" Price");

        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });

        descriptionLabel.setText("Description");

        searchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFieldActionPerformed(evt);
            }
        });
        searchField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchFieldKeyPressed(evt);
            }
        });

        headingLabel.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        headingLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headingLabel.setText("Product Details");

<<<<<<< HEAD
=======
<<<<<<< HEAD
=======
>>>>>>> refs/heads/Aniket2
        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

<<<<<<< HEAD
=======
>>>>>>> origin/Louisnew
>>>>>>> refs/heads/Aniket2
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
<<<<<<< HEAD
=======
<<<<<<< HEAD
                .addGap(122, 122, 122)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(viewButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(updateButton))
=======
>>>>>>> refs/heads/Aniket2
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
<<<<<<< HEAD
=======
>>>>>>> origin/Louisnew
>>>>>>> refs/heads/Aniket2
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                                            .addComponent(priceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(descriptionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(priceField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(descriptionField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
<<<<<<< HEAD
=======
<<<<<<< HEAD
                                        .addComponent(searchField)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(124, 124, 124)
                        .addComponent(deleteButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(113, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addComponent(headingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
=======
>>>>>>> refs/heads/Aniket2
                                        .addComponent(searchField))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(updateButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(deleteButton)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(saveButton))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(headingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(121, Short.MAX_VALUE))
<<<<<<< HEAD
=======
>>>>>>> origin/Louisnew
>>>>>>> refs/heads/Aniket2
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteButton)
<<<<<<< HEAD
=======
<<<<<<< HEAD
                    .addComponent(viewButton)
                    .addComponent(updateButton))
                .addGap(14, 14, 14)
=======
>>>>>>> refs/heads/Aniket2
                    .addComponent(updateButton)
                    .addComponent(saveButton))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
<<<<<<< HEAD
=======
>>>>>>> origin/Louisnew
>>>>>>> refs/heads/Aniket2
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceLabel)
                    .addComponent(priceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descriptionLabel)
                    .addComponent(descriptionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
<<<<<<< HEAD
                .addContainerGap(241, Short.MAX_VALUE))
=======
<<<<<<< HEAD
                .addGap(170, 170, 170)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(91, Short.MAX_VALUE))
=======
                .addContainerGap(241, Short.MAX_VALUE))
>>>>>>> origin/Louisnew
>>>>>>> refs/heads/Aniket2
        );
    }// </editor-fold>//GEN-END:initComponents

    private void descriptionFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descriptionFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descriptionFieldActionPerformed

<<<<<<< HEAD
=======
<<<<<<< HEAD
    private void viewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewButtonActionPerformed
        // TODO add your handling code here:
        int selectedIndex = userTable.getSelectedRow();
        if (selectedIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row to be viewed", "Error - No selection", JOptionPane.WARNING_MESSAGE);
        } else {
            DefaultTableModel model = (DefaultTableModel) userTable.getModel();
            Product selectedProd = (Product) model.getValueAt(selectedIndex, 0);
            nameField.setText(selectedProd.getProductName());
            priceField.setText(String.valueOf(selectedProd.getPrice()));
            descriptionField.setText(selectedProd.getProductDescription());
        }
    }//GEN-LAST:event_viewButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        int selectedIndex = userTable.getSelectedRow();
        if (selectedIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row to be deleted", "Error - No selection", JOptionPane.WARNING_MESSAGE);
        } else {
            DefaultTableModel model = (DefaultTableModel) userTable.getModel();
            Product selectedProducts = (Product) model.getValueAt(selectedIndex, 0);
            products.removeUser(selectedProducts);
            JOptionPane.showMessageDialog(this, "User Information is deleted successfully.");
            populateTable();
=======
>>>>>>> refs/heads/Aniket2
    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed

        int selectedIdx = userTable.getSelectedRow();
        if (selectedIdx == -1){
            JOptionPane.showMessageDialog(this, "Please selected a user to delete", "Cannot delete User",WIDTH);
            return;
        }
        try{
            selectedProduct = products.get(selectedIdx);
            System.out.print(selectedProduct.getProductName());
            DatabaseConnector.deleteUser(selectedProduct);
            JOptionPane.showMessageDialog(null, "User Deleted Successfully", "Successfully Deleted", HEIGHT);
            clearFields();
            populateTable();
        }catch(Exception e){
        JOptionPane.showMessageDialog(this, e.getMessage());
<<<<<<< HEAD
=======
>>>>>>> origin/Louisnew
>>>>>>> refs/heads/Aniket2
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
<<<<<<< HEAD
=======
<<<<<<< HEAD
        Product selectedProduct;
        int selectedIndex = userTable.getSelectedRow();
        if (selectedIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row to be updated", "Error - No selection", JOptionPane.WARNING_MESSAGE);
        } else {
            DefaultTableModel model = (DefaultTableModel) userTable.getModel();
            selectedProduct = (Product) model.getValueAt(selectedIndex, 0);
            selectedProduct.setProductName(nameField.getText());
            selectedProduct.setPrice(Integer.parseInt(priceField.getText()));
            selectedProduct.setProductDescription(descriptionField.getText());

            JOptionPane.showMessageDialog(this, "Employee Details Updated", "Success", HEIGHT);
        }
    
=======
>>>>>>> refs/heads/Aniket2
        int selectedIdx = userTable.getSelectedRow();
        if (selectedIdx == -1){
            JOptionPane.showMessageDialog(this, "Please select a user to edit", "Edit Users", HEIGHT);
            return;
        }
        selectedProduct = products.get(selectedIdx);
        nameField.setText(selectedProduct.getProductName());
        priceField.setText(Integer.toString(selectedProduct.getPrice()));
        descriptionField.setText(selectedProduct.getProductDescription());
<<<<<<< HEAD
=======
>>>>>>> origin/Louisnew
>>>>>>> refs/heads/Aniket2
    }//GEN-LAST:event_updateButtonActionPerformed

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void searchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchFieldActionPerformed

    private void searchFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchFieldKeyPressed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) userTable.getModel();
        TableRowSorter<DefaultTableModel> t = new TableRowSorter<DefaultTableModel>(model);
        userTable.setRowSorter(t);
        t.setRowFilter(RowFilter.regexFilter(searchField.getText().trim()));
    }//GEN-LAST:event_searchFieldKeyPressed
<<<<<<< HEAD
=======
<<<<<<< HEAD
        
    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) userTable.getModel();
        model.setRowCount(0);
        for (Product u : products.getAllProducts()) {
            Object[] row = new Object[2];
            row[0] = u;
            row[1] = u.getPrice();
            model.addRow(row);
    }
            clearFields();
=======
>>>>>>> refs/heads/Aniket2

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        Product newProd = new Product();
        try{
            newProd.setProductName(nameField.getText());
            newProd.setPrice(Integer.parseInt(priceField.getText()));
            newProd.setProductDescription(descriptionField.getText());
            
            DatabaseConnector.editUser(selectedProduct, newProd);
            JOptionPane.showMessageDialog(null, "Product Edit Successfully", "Successfully Edit", HEIGHT);
            clearFields();
            populateTable();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }//GEN-LAST:event_saveButtonActionPerformed
        
    public void populateTable() {
        try{
            this.products = DatabaseConnector.getAllusers();
            DefaultTableModel model = (DefaultTableModel) userTable.getModel();
            model.setRowCount(0);
            for (Product u:products){
                Object[] row = new Object[4];
                row[0] = u.getProductId();
                row[1] = u.getProductName();
                row[2] = u.getPrice();
                row[3] = u.getProductDescription();
                model.addRow(row);
            }
            clearFields();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
<<<<<<< HEAD
=======
>>>>>>> origin/Louisnew
>>>>>>> refs/heads/Aniket2
}
    
    private void clearFields() {
        nameField.setText("");
        priceField.setText("");
        descriptionField.setText("");

        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField descriptionField;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JLabel headingLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField priceField;
    private javax.swing.JLabel priceLabel;
<<<<<<< HEAD
=======
<<<<<<< HEAD
    private javax.swing.JTextField searchField;
    private javax.swing.JButton updateButton;
    private javax.swing.JTable userTable;
    private javax.swing.JButton viewButton;
=======
>>>>>>> refs/heads/Aniket2
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField searchField;
    private javax.swing.JButton updateButton;
    private javax.swing.JTable userTable;
<<<<<<< HEAD
=======
>>>>>>> origin/Louisnew
>>>>>>> refs/heads/Aniket2
    // End of variables declaration//GEN-END:variables
    }

